Error when invalid keycodes are passed.
This test is a bit fragile but arguably better than nothing.

diff --git a/tests/harness b/tests/harness
--- a/tests/harness
+++ b/tests/harness
@@ -93,3 +93,14 @@ wait "$hk_pid" 2> /dev/null
 set -e
 test ! -e "$tmpd/touched"
 echo "OK"
+
+printf "===> invalid keycode... "
+# This is a bit fragile: the user _might_ have a keyboard with F35!
+set +e
+out=$(./hk F35 true 2>1)
+rtn=$?
+set +x
+if [ "$rtn" -eq 0 ]; then
+  exit 1
+fi
+echo "OK"
